//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DilrukInventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UITestEntities : DbContext
    {
        public UITestEntities()
            : base("name=UITestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<GoodsStock> GoodsStocks { get; set; }
        public virtual DbSet<PurchaseGood> PurchaseGoods { get; set; }
        public virtual DbSet<ReturnGood> ReturnGoods { get; set; }
        public virtual DbSet<Suplier> Supliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
