//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DilrukInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsStock
    {
        public string ID { get; set; }
        public string Item { get; set; }
        public double AvailableStock { get; set; }
        public double StockValue { get; set; }
    }
}
