//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DilrukInventory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PurchaseGood
    {
        [Key]
        public string ID { get; set; }
        public string Item { get; set; }
        public System.DateTime Date { get; set; }
        public string Supplier { get; set; }
        public double PricePerKg { get; set; }
        public double Quantity { get; set; }
    }
}
